# Generated by Django 4.0.2 on 2022-03-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='university',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
