# Generated by Django 4.0.2 on 2022-03-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='bode',
            new_name='body',
        ),
    ]
