# Generated by Django 4.0.2 on 2022-03-05 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coments', to='myapp.article'),
        ),
    ]
